Setting up CI workflow for Github action
AbiOnMac/rdydev pull request #4
Opened 2023-11-26 23:56 UTC by AbiOnMac

## Description

Please include a summary of the changes and the issue that is being fixed. Please also include relevant motivation and context.

Fixes # (issue)

## Type of change
Updating CI workflow of GitHub action to run in each pull request
![Screenshot 2023-11-27 at 10 45 37 am](https://github.com/AbiOnMac/rdydev/assets/104052078/22639f9a-521d-41f6-acfd-bc63efb95b48)

Please select the relevant option.

- [ ] Bug fix
- [ ] New feature
- [ ] Breaking change
- [ ] Other

## Checklist

Please review the following checklist and ensure all tasks are completed before submitting the pull request:

- [ ] I have performed a self-review of my own code
- [ ] I have added tests that prove my fix is effective or that my feature works

2023-11-27 02:38 UTC, josh-cooper approved these changes

2023-12-06 07:29 UTC, m0xfff requested changes
Nice work, just a few changes 👍

2023-12-06 07:29 UTC, m0xfff commented on .github/workflows/rspec.yml
> +      - '*'
This would trigger the workflow on any push to any branch, which you probably don't want. Better to only trigger the action on push to `main` & `develop`.
```suggestion
on:
  pull_request:
  push:
    branches:
      - main
      - develop
```

2023-12-06 07:29 UTC, m0xfff commented on app/controllers/students_controller.rb
> +  end
I recommend initializing the `@student` instance variable in a `before_action` callback. That way you don't have to send `set_student` in each controller action e.g.

```
class StudentsController < ApplicationController
  before_action :set_student, only: [:show, :edit, :update, :destroy]

  ...

  def show
  end

  ...
end
```

2023-12-06 07:29 UTC, m0xfff commented on app/controllers/students_controller.rb
>      @students = Student.paginate(page: params[:page], per_page: 10)
I understand this is outside the scope of this PR, but I spot a magic number!

I recommend moving the `per_page` value into a constant e.g.

```ruby
class StudentsController < ApplicationController
  DEFAULT_PER_PAGE = 10

  def index
    @students = Student.paginate(page: params[:page], per_page: DEFAULT_PER_PAGE)
  end
```

2023-12-06 07:29 UTC, m0xfff commented on app/views/students/shared/_form.html.erb
Personally, I wouldn't place a form partial within a directory called shared. I'd keep it in the students view directory with the other views.

2023-12-06 07:29 UTC, m0xfff commented on app/views/students/index.html.erb
> +        <th>Action</th>
```suggestion
        <th colspan="3">Action</th>
```

2023-12-06 07:29 UTC, m0xfff commented on app/views/students/index.html.erb
> +      </td>
```suggestion
      <td><%= link_to 'Show', student_path(student) %></td>
      <td><%= link_to 'Edit', edit_student_path(student) %></td>
      <td><%= link_to 'Delete', student_path(student), method: :delete, data: { confirm: 'Are you sure?' } %></td>
```

2023-12-10 23:57 UTC, josh-cooper approved these changes

2023-12-10 23:59 UTC, merged